version: '3'
services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment: 
    - POSTGRES_PASSWORD=postgres
    volumes:
    - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  admin:
    image: adminer:latest
    restart: always
    depends_on: 
      - postgres
    ports:
      - 8080:8080